//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagement_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int EnrollmentID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string Status { get; set; }
    
        public virtual Enrollments Enrollments { get; set; }
    }
}
